[build]
  publish = "public"
  command = "npm run build"

[[headers]]
for = "*.js"
[headers.values]
Content-Type = "application/javascript"

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
